apiVersion: v1
kind: Pod
spec:
  containers:
    - name: maven
      image: maven:3.9.9-eclipse-temurin-17
      command: ["sleep"]
      args: ["infinity"]

    - name: docker
      image: docker:24-dind
      securityContext:
        privileged: true
      command: ["sleep"]
      args: ["infinity"]
